def help():
    print('========== HELP ==========')
    print('register - untuk melakukan registrasi user baru')
    print('login - untuk masuk ke dalam akun user yang telah teregristasi')
    print('carirarity - untuk mencari gadget berdasarkan raritynya')
    print('caritahun - untuk mencari gadget berdasarkan tahun ditemukannya')
    print('tambahitem - untuk menambah item ke dalam inventori')
    print('hapusitem - untuk menghapus item dari inventori')
    print('ubahjumlah - untuk mengubah jumlah gadget atau consumable yang ada di inventori')
    print('pinjam - untuk meminjam gadget dari inventori')
    print('kembalikan - untuk mengembalikan gadget yang telah dipinjam kembali ke inventori')
    print('minta - untuk meminta consumable dari inventori')
    print('riwayatpinjam - untuk melihat riwayat peminjaman gadget')
    print('riwayatkembali - untuk melihat riwayat pengembalian gadget')
    print('riwayatambil - untuk melihat riwayat pengambilan consumable')
    print('save - untuk menyimpan perubahan data pada file')
    print('help - untuk memberikan panduan penggunaan sistem')
    print('exit - untuk keluar dari aplikasi')

